const createEventsExamples: Record<
  string,
  {
    title: string;
    shortDescription: string;
    description: string;
    eventType: string;
    isRestricted: boolean;
    autoEnroll: boolean;
    startDatetime: string;
    endDatetime: string;
    location?: string;
    longitude?: number;
    latitude?: number;
    onlineProvider?: string;
    meetingType?: string;
    approvalType?: number;
    timezone?: string;
    isMeetingNew?: boolean;
    onlineDetails?: any;
    maxAttendees: number;
    attendees?: string[];
    recordings: any;
    status: string;
    createdBy: string;
    updatedBy: string;
    idealTime: number;
    registrationStartDate?: string;
    registrationEndDate?: string;
    isRecurring: boolean;
    recurrencePattern?: any;
    metaData: any;
    erMetaData: any;
    platformIntegration?: boolean;
  }
> = {
  OfflineEvent: {
    title: 'Sample Offline Event',
    shortDescription: 'This is a sample offline event',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    eventType: 'offline',
    isRestricted: true,
    autoEnroll: true,
    startDatetime: '2024-03-18T10:00:00Z',
    endDatetime: '2024-03-18T12:00:00Z',
    location: 'Event Location',
    longitude: 18.508345134886994,
    latitude: 18.508345134886994,
    maxAttendees: 100,
    attendees: [
      'eff008a8-2573-466d-b877-fddf6a4fc13e',
      'e9fec05a-d6ab-44be-bfa4-eaeef2ef8fe9',
    ],
    recordings: { url: 'https://example.com/recording' },
    status: 'live',
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 120,
    isRecurring: false,
    metaData: {},
    erMetaData: {},
  },
  OnlineEvent: {
    title: 'Sample Online Event',
    shortDescription: 'This is a sample online event',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    eventType: 'online',
    isRestricted: true,
    autoEnroll: true,
    startDatetime: '2024-03-18T10:00:00Z',
    endDatetime: '2024-03-18T12:00:00Z',
    onlineProvider: 'Zoom',
    meetingType: 'meeting',
    approvalType: 0,
    timezone: 'Asia/Kolkata',
    isMeetingNew: false,
    onlineDetails: {
      url: 'https://zoom.us/j/123456789?pwd=meetingpassword',
      id: 'meeting-id',
    },
    maxAttendees: 100,
    attendees: [
      'eff008a8-2573-466d-b877-fddf6a4fc13e',
      'e9fec05a-d6ab-44be-bfa4-eaeef2ef8fe9',
    ],
    recordings: { url: 'https://example.com/recording' },
    status: 'live',
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 120,
    isRecurring: false,
    metaData: {},
    erMetaData: {},
  },
  AutoCreateMeeting: {
    title: 'Auto-Create Meeting Event',
    shortDescription: 'This event will automatically create a Zoom meeting',
    description: 'This event demonstrates automatic meeting creation',
    eventType: 'online',
    isRestricted: true,
    autoEnroll: true,
    startDatetime: '2024-03-18T10:00:00Z',
    endDatetime: '2024-03-18T12:00:00Z',
    onlineProvider: 'Zoom',
    meetingType: 'meeting',
    approvalType: 0,
    timezone: 'America/New_York',
    isMeetingNew: true,
    maxAttendees: 100,
    attendees: [
      'eff008a8-2573-466d-b877-fddf6a4fc13e',
      'e9fec05a-d6ab-44be-bfa4-eaeef2ef8fe9',
    ],
    recordings: { url: 'https://example.com/recording' },
    status: 'live',
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 120,
    isRecurring: false,
    metaData: {},
    erMetaData: {},
  },
  AutoCreateWebinar: {
    title: 'Auto-Create Webinar Event',
    shortDescription: 'This event will automatically create a Zoom webinar',
    description: 'This event demonstrates automatic webinar creation',
    eventType: 'online',
    isRestricted: true,
    autoEnroll: true,
    startDatetime: '2024-01-20T14:00:00Z',
    endDatetime: '2024-01-20T15:30:00Z',
    onlineProvider: 'Zoom',
    meetingType: 'webinar',
    approvalType: 1,
    timezone: 'Europe/London',
    isMeetingNew: true,
    maxAttendees: 100,
    attendees: [
      'eff008a8-2573-466d-b877-fddf6a4fc13e',
      'e9fec05a-d6ab-44be-bfa4-eaeef2ef8fe9',
    ],
    recordings: { url: 'https://example.com/recording' },
    status: 'live',
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 120,
    isRecurring: false,
    metaData: {},
    erMetaData: {},
  },
  ExistingWebinar: {
    title: 'Existing Webinar Event',
    shortDescription: 'This event uses an existing Zoom webinar',
    description: 'This event demonstrates using an existing webinar',
    eventType: 'online',
    isRestricted: true,
    autoEnroll: true,
    startDatetime: '2024-01-20T14:00:00Z',
    endDatetime: '2024-01-20T15:30:00Z',
    onlineProvider: 'Zoom',
    meetingType: 'webinar',
    approvalType: 2,
    timezone: 'Asia/Tokyo',
    isMeetingNew: false,
    onlineDetails: {
      url: 'https://zoom.us/w/123456789?pwd=webinarpassword',
      id: 'webinar-id',
    },
    maxAttendees: 100,
    attendees: [
      'eff008a8-2573-466d-b877-fddf6a4fc13e',
      'e9fec05a-d6ab-44be-bfa4-eaeef2ef8fe9',
    ],
    recordings: { url: 'https://example.com/recording' },
    status: 'live',
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 120,
    isRecurring: false,
    metaData: {},
    erMetaData: {},
  },
  RecurringOnlineDailyByEndDate: {
    title: 'Sample OnlineDailyByEndDate Event',
    shortDescription: 'This is a sample event',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    eventType: 'online',
    isRestricted: true,
    autoEnroll: true,
    startDatetime: '2024-12-18T10:00:00Z',
    endDatetime: '2024-12-18T11:00:00Z',
    onlineProvider: 'Zoom',
    meetingType: 'meeting',
    approvalType: 0,
    timezone: 'Asia/Kolkata',
    isMeetingNew: false,
    onlineDetails: {
      url: 'https://zoom.us/j/99201586505?pwd=ZA8uek6tYu0LQTPbW2GgIORpNDmv7j',
      id: 'meeting-id',
    },
    maxAttendees: 100,
    attendees: [],
    recordings: {
      url: 'https://zoom.com/recording',
    },
    status: 'live',
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 120,
    isRecurring: true,
    recurrencePattern: {
      frequency: 'daily',
      interval: 1,
      endCondition: {
        type: 'endDate',
        value: '2024-12-25T11:00:00Z',
      },
      recurringStartDate: '2024-03-18T10:00:00Z',
    },
    metaData: { cohortId: '3218bb35-a87d-4adf-b305-b205286fe320' },
    erMetaData: {},
  },
  RecurringOnlineDailyByOccurrences: {
    title: 'Sample OnlineDailyByOccurrences Event',
    shortDescription: 'This is a sample event',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    eventType: 'online',
    isRestricted: true,
    autoEnroll: true,
    startDatetime: '2024-12-18T10:00:00Z',
    endDatetime: '2024-12-18T11:00:00Z',
    onlineProvider: 'Zoom',
    meetingType: 'meeting',
    approvalType: 0,
    timezone: 'Asia/Kolkata',
    isMeetingNew: false,
    onlineDetails: {
      url: 'https://zoom.us/j/99201586505?pwd=ZA8uek6tYu0LQTPbW2GgIORpNDmv7j',
      id: 'meeting-id',
    },
    maxAttendees: 100,
    attendees: [],
    recordings: {
      url: 'https://zoom.com/recording',
    },
    status: 'live',
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 120,
    isRecurring: true,
    recurrencePattern: {
      frequency: 'daily',
      interval: 1,
      endCondition: {
        type: 'occurrences',
        value: '20',
      },
      recurringStartDate: '2024-03-18T10:00:00Z',
    },
    metaData: { cohortId: '3218bb35-a87d-4adf-b305-b205286fe320' },
    erMetaData: {},
  },
  RecurringOfflineDailyByEndDate: {
    title: 'Sample OfflineDailyByEndDate Event',
    shortDescription: 'This is a sample event',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    eventType: 'offline',
    isRestricted: true,
    autoEnroll: true,
    startDatetime: '2024-12-18T10:00:00Z',
    endDatetime: '2024-12-18T11:00:00Z',
    location: 'Kothrud',
    maxAttendees: 100,
    attendees: [],
    recordings: {
      url: 'https://zoom.com/recording',
    },
    status: 'live',
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 120,
    isRecurring: true,
    recurrencePattern: {
      frequency: 'daily',
      interval: 1,
      endCondition: {
        type: 'endDate',
        value: '2024-12-25T11:00:00Z',
      },
      recurringStartDate: '2024-03-18T10:00:00Z',
    },
    metaData: {
      cohortId: '3218bb35-a87d-4adf-b305-b205286fe320',
    },
    erMetaData: {},
  },
  RecurringOfflineDailyByOccurrence: {
    title: 'Sample OfflineDailyByOccurrence Event',
    shortDescription: 'This is a sample event',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    eventType: 'offline',
    isRestricted: true,
    autoEnroll: true,
    startDatetime: '2024-12-18T10:00:00Z',
    endDatetime: '2024-12-18T11:00:00Z',
    location: 'Kothrud',
    maxAttendees: 100,
    attendees: [],
    recordings: {
      url: 'https://zoom.com/recording',
    },
    status: 'live',
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 120,
    isRecurring: true,
    recurrencePattern: {
      frequency: 'daily',
      interval: 1,
      endCondition: {
        type: 'occurrences',
        value: '20',
      },
      recurringStartDate: '2024-03-18T10:00:00Z',
    },
    metaData: {
      cohortId: '3218bb35-a87d-4adf-b305-b205286fe320',
    },
    erMetaData: {},
  },
  RecurringOnlineWeeklyByEndDate: {
    title: 'Sample OnlineWeeklyByEndDate Event',
    shortDescription: 'This is a sample event',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    eventType: 'online',
    isRestricted: true,
    autoEnroll: true,
    startDatetime: '2024-12-18T10:00:00Z',
    endDatetime: '2024-12-18T11:00:00Z',
    onlineProvider: 'Zoom',
    meetingType: 'meeting',
    approvalType: 0,
    timezone: 'Asia/Kolkata',
    isMeetingNew: false,
    onlineDetails: {
      url: 'https://zoom.us/j/99201586505?pwd=ZA8uek6tYu0LQTPbW2GgIORpNDmv7j',
      id: 'meeting-id',
    },
    maxAttendees: 100,
    attendees: [],
    recordings: {
      url: 'https://example.com/recording',
    },
    status: 'live',
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 120,
    isRecurring: true,
    recurrencePattern: {
      frequency: 'weekly',
      interval: 1,
      daysOfWeek: [3, 5], //  Wednesday ,friday
      endCondition: {
        type: 'endDate',
        value: '2024-12-25T11:00:00Z',
      },
      recurringStartDate: '2024-12-18T10:00:00Z',
    },
    metaData: {},
    erMetaData: {},
  },
  RecurringOnlineWeeklyByOccurrences: {
    title: 'Sample OnlineWeeklyByOccurrences Event',
    shortDescription: 'This is a sample event',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    eventType: 'online',
    isRestricted: true,
    autoEnroll: true,
    startDatetime: '2024-12-18T10:00:00Z',
    endDatetime: '2024-12-18T11:00:00Z',
    onlineProvider: 'Zoom',
    meetingType: 'meeting',
    approvalType: 0,
    timezone: 'Asia/Kolkata',
    isMeetingNew: false,
    onlineDetails: {
      url: 'https://zoom.us/j/99201586505?pwd=ZA8uek6tYu0LQTPbW2GgIORpNDmv7j',
      id: 'meeting-id',
    },
    maxAttendees: 100,
    attendees: [],
    recordings: {
      url: 'https://example.com/recording',
    },
    status: 'live',
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 120,
    isRecurring: true,
    recurrencePattern: {
      frequency: 'weekly',
      interval: 1,
      daysOfWeek: [3, 5], //  Wednesday ,friday
      endCondition: {
        type: 'occurrences',
        value: '20',
      },
      recurringStartDate: '2024-12-18T10:00:00Z',
    },
    metaData: {},
    erMetaData: {},
  },
  RecurringOfflineWeeklyByEndDate: {
    title: 'Sample Event',
    shortDescription: 'This is a sample event',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    eventType: 'offline',
    isRestricted: true,
    autoEnroll: true,
    startDatetime: '2024-12-18T10:00:00Z',
    endDatetime: '2024-12-18T11:00:00Z',
    location: 'Kothrud',
    maxAttendees: 100,
    attendees: [],
    recordings: {
      url: 'https://example.com/recording',
    },
    status: 'live',
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 120,
    isRecurring: true,
    recurrencePattern: {
      frequency: 'weekly',
      interval: 1,
      daysOfWeek: [3, 5], //  Wednesday ,friday
      endCondition: {
        type: 'endDate',
        value: '2024-12-25T11:00:00Z',
      },
      recurringStartDate: '2024-12-18T10:00:00Z',
    },
    metaData: {},
    erMetaData: {},
  },
  RecurringOfflineWeeklyByOccurrence: {
    title: 'Sample Event',
    shortDescription: 'This is a sample event',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    eventType: 'offline',
    isRestricted: true,
    autoEnroll: true,
    startDatetime: '2024-12-18T10:00:00Z',
    endDatetime: '2024-12-18T11:00:00Z',
    location: 'Kothrud',
    maxAttendees: 100,
    attendees: [],
    recordings: {
      url: 'https://example.com/recording',
    },
    status: 'live',
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 120,
    isRecurring: true,
    recurrencePattern: {
      frequency: 'weekly',
      interval: 1,
      daysOfWeek: [3, 5], //  Wednesday ,friday
      endCondition: {
        type: 'occurrences',
        value: '20',
      },
      recurringStartDate: '2024-12-18T10:00:00Z',
    },
    metaData: {},
    erMetaData: {},
  },
  NonRecurringOffline: {
    title: 'Sample Event',
    shortDescription: 'This is a sample event',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    eventType: 'offline',
    isRestricted: true,
    autoEnroll: true,
    startDatetime: '2024-12-18T10:00:00Z',
    endDatetime: '2024-12-18T11:00:00Z',
    location: 'Kothrud',
    maxAttendees: 100,
    attendees: [],
    recordings: {
      url: 'https://example.com/recording',
    },
    status: 'live',
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 120,
    isRecurring: false,
    metaData: {},
    erMetaData: {},
  },
  NonRecurringOnline: {
    title: 'Sample NonRecurringOnline Event',
    shortDescription: 'This is a sample event',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    eventType: 'online',
    isRestricted: true,
    autoEnroll: true,
    startDatetime: '2024-12-18T10:00:00Z',
    endDatetime: '2024-12-18T11:00:00Z',
    onlineProvider: 'Zoom',
    meetingType: 'meeting',
    approvalType: 0,
    timezone: 'Asia/Kolkata',
    isMeetingNew: false,
    onlineDetails: {
      url: 'https://zoom.us/j/99201586505?pwd=ZA8uek6tYu0LQTPbW2GgIORpNDmv7j',
      id: 'meeting-id',
    },
    maxAttendees: 100,
    attendees: [],
    recordings: {
      url: 'https://example.com/recording',
    },
    status: 'live',
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 120,
    isRecurring: false,
    metaData: {},
    erMetaData: {},
  },
  CreateEventWithNewMeeting: {
    title: 'Create Event with New Meeting',
    shortDescription: 'This is a sample event with new meeting',
    description: 'This is a sample event with new meeting description',
    eventType: 'online',
    onlineProvider: 'Zoom',
    isMeetingNew: true,
    meetingType: 'meeting',
    approvalType: 0,
    timezone: 'Asia/Kolkata',
    platformIntegration: true,
    startDatetime: '2024-12-18T10:00:00Z',
    endDatetime: '2024-12-18T11:00:00Z',
    isRestricted: true,
    autoEnroll: true,
    status: 'live',
    isRecurring: false,
    maxAttendees: 100,
    attendees: ['eff008a8-2573-466d-b877-fddf6a4fc13e'],
    recordings: { url: 'https://example.com/recording' },
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 60,
    metaData: {},
    erMetaData: {},
  },
  CreateEventWithNewWebinar: {
    title: 'Create Event with New Webinar',
    shortDescription: 'This is a sample event with new webinar',
    description: 'This is a sample event with new webinar description',
    eventType: 'online',
    onlineProvider: 'Zoom',
    isMeetingNew: true,
    meetingType: 'webinar',
    approvalType: 1,
    timezone: 'America/New_York',
    platformIntegration: true,
    startDatetime: '2024-12-18T10:00:00Z',
    endDatetime: '2024-12-18T11:00:00Z',
    isRestricted: false,
    autoEnroll: true,
    status: 'live',
    isRecurring: false,
    maxAttendees: 200,
    attendees: ['eff008a8-2573-466d-b877-fddf6a4fc13e'],
    recordings: { url: 'https://example.com/recording' },
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 60,
    metaData: {},
    erMetaData: {},
  },
  CreateEventWithExistingMeeting: {
    title: 'Create Event with Existing Meeting',
    shortDescription: 'This is a sample event with existing meeting',
    description: 'This is a sample event with existing meeting description',
    eventType: 'online',
    onlineProvider: 'Zoom',
    isMeetingNew: false,
    meetingType: 'meeting',
    approvalType: 0,
    timezone: 'Europe/London',
    platformIntegration: false,
    onlineDetails: {
      onlineProvider: 'Zoom',
      id: '123-456-0000',
      url: 'http://zoom.us/j/mymeeting?pwd=xyz',
      password: 'xxxxxxx',
      occurrenceId: '',
      providerGenerated: false,
    },
    startDatetime: '2024-12-18T10:00:00Z',
    endDatetime: '2024-12-18T11:00:00Z',
    isRestricted: true,
    autoEnroll: true,
    status: 'live',
    isRecurring: false,
    maxAttendees: 100,
    attendees: ['eff008a8-2573-466d-b877-fddf6a4fc13e'],
    recordings: { url: 'https://example.com/recording' },
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 60,
    metaData: {},
    erMetaData: {},
  },
  CreateEventWithExistingWebinar: {
    title: 'Create Event with Existing Webinar',
    shortDescription: 'This is a sample event with existing webinar',
    description: 'This is a sample event with existing webinar description',
    eventType: 'online',
    onlineProvider: 'Zoom',
    isMeetingNew: false,
    meetingType: 'webinar',
    approvalType: 2,
    timezone: 'Asia/Tokyo',
    platformIntegration: false,
    onlineDetails: {
      onlineProvider: 'Zoom',
      id: '123-456-0000',
      url: 'http://zoom.us/w/mywebinar?pwd=xyz',
      password: 'xxxxxxx',
      occurrenceId: '',
      providerGenerated: false,
    },
    startDatetime: '2024-12-18T10:00:00Z',
    endDatetime: '2024-12-18T11:00:00Z',
    isRestricted: false,
    autoEnroll: true,
    status: 'live',
    isRecurring: false,
    maxAttendees: 200,
    attendees: ['eff008a8-2573-466d-b877-fddf6a4fc13e'],
    recordings: { url: 'https://example.com/recording' },
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 60,
    metaData: {},
    erMetaData: {},
  },
  CreateEventWithLocalOnly: {
    title: 'Create Event with Local Only (No Platform Integration)',
    shortDescription: 'This is a sample event with no platform integration',
    description:
      'This is a sample event with no platform integration description',
    eventType: 'online',
    onlineProvider: 'Zoom',
    isMeetingNew: true,
    meetingType: 'meeting',
    approvalType: 0,
    timezone: 'UTC',
    platformIntegration: false,
    startDatetime: '2024-12-18T10:00:00Z',
    endDatetime: '2024-12-18T11:00:00Z',
    isRestricted: true,
    autoEnroll: true,
    status: 'live',
    isRecurring: false,
    maxAttendees: 100,
    attendees: ['eff008a8-2573-466d-b877-fddf6a4fc13e'],
    recordings: { url: 'https://example.com/recording' },
    createdBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    updatedBy: 'eff008a8-2573-466d-b877-fddf6a4fc13e',
    idealTime: 60,
    metaData: {},
    erMetaData: {},
  },
};

export const createEventsExamplesForSwagger = Object.entries(
  createEventsExamples,
).reduce(
  (acc, [key, value]) => {
    acc[key] = {
      summary: `Example for ${key}`,
      description: `Detailed example for ${key}`,
      value, // Use the example value as-is
    };
    return acc;
  },
  {} as Record<string, { summary: string; description: string; value: any }>,
);
