apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: event-management
  name: event-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-management
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: event-management
    spec:
      containers:
      - image: ${ECR_REPOSITORY}:${IMAGE_TAG}
        imagePullPolicy: "Always"
        name: event-management
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: event-service-config
        resources:
          requests:
            cpu: "7000m"
            memory: "700Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: event-management
spec:
  type: ClusterIP
  ports:
  - port: 3001
    protocol: TCP
  selector:
    app: event-management
